{% set name = "Routes" %}
{% set version = "2.4.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "26ee43340fca5a32769ffe0c58edcb396ccce6bc1dfa689ddf844d50877355fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - six
    - repoze.lru >=0.3

test:
  imports:
    - routes

about:
  home: https://routes.readthedocs.io/
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Routing Recognition and Generation Tools
  dev_url: https://github.com/bbangert/routes
  doc_url: https://routes.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
