{% set name = "Routes" %}
{% set version = "2.5.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "1dfa907de2f0517db33717faf785fb2dca1f0f40067a0619b33feae17e23d437" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - repoze.lru >=0.3

test:
  imports:
    - routes

about:
  home: https://routes.readthedocs.io/
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Routing Recognition and Generation Tools
  dev_url: https://github.com/bbangert/routes
  doc_url: https://routes.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
